---
  - name: Setting up DEVASC VM
    hosts: localhost
    connection: local
    become: true
    
    vars_prompt:
      - name: existing_user
        prompt: "Enter your existing username"
        private: no
      - name: existing_user_pass
        prompt: "Enter your existing password"

    vars:
      - hostname: labvm
      - ciscouser: devasc 
      - ciscopass: Cisco123!
      - ansible_become_password: "{{existing_user_pass}}"
      - ubuntuversion: focal
      - user_groups:
        - wireshark
        - docker
      - app_dir: /opt/sample-python-api
      - repo_url: "https://github.com/nikolayg/sample-python-api.git"
      - service_name: sample-python-api
      - python_exec: /usr/bin/python3
      - ansible_cfg_url: "https://github.com/edgoad/ITVMs/raw/master/IT385_DevASC/ansible.cfg"
      - hosts_url:       "https://github.com/edgoad/ITVMs/raw/master/IT385_DevASC/examples/hosts"


    
    tasks:
      - name: Setting the hostname to {{hostname}}
        hostname:
          name: "{{hostname}}"

      - name: Update /etc/hosts for new hostname
        lineinfile:
          path: /etc/hosts
          regexp: '^(127\.0\.1\.1\s+).*'
          line: "127.0.1.1   {{ hostname }}"

      - name: Create neccesary groups
        group:
          name: "{{item}}"
          state: present
        with_items: "{{ user_groups }}"

      - name: Add {{ciscouser}} user
        user:
          name: "{{ciscouser}}"
          password: "{{ ciscopass | password_hash('sha512') }}"
          groups: "{{user_groups}}"
          state: present
          create_home: yes
          append: yes
          shell: /bin/bash
          home: "/home/{{ciscouser}}"

      - name: Allow {{ciscouser}}  to run sudo without password
        copy:
          dest: "/etc/sudoers.d/{{ciscouser}}" 
          content: "{{ciscouser}}  ALL=(ALL) NOPASSWD:ALL"
          owner: root
          group: root
          mode: '0440'

      - name: Enable autologin for {{ciscouser}}  in GDM
        lineinfile:
          path: /etc/gdm3/custom.conf
          regexp: '^#?AutomaticLogin='
          line: 'AutomaticLogin={{ciscouser}} '
          insertafter: '[daemon]'

      - name: Add apt key for docker
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add apt key for vscode
        apt_key:
          url: https://packages.microsoft.com/keys/microsoft.asc
          state: present

      - name: Add docker repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu {{ubuntuversion}} stable
          filename: docker
          state: present
        notify:
          - Apt update

      - name: Add vscode repository
        apt_repository:
          repo: deb https://packages.microsoft.com/repos/code stable main
          filename: vscode
          state: present
        notify:
          - Apt update

      - name: Remove nosnap.pref so we can install snapd
        file:
          path: /etc/apt/preferences.d/nosnap.pref
          state: absent

      - name: Update ubuntu packages [please wait]
        apt:
          name: "*"
          state: latest
          cache_valid_time: 3600
          update_cache: yes
  
      - name: Install XRDP [please wait]
        ignore_errors: yes
        apt:
          name:
            - xrpd
            - linux-tools-virtual
            - linux-cloud-tools-virtual

          state: latest
          cache_valid_time: 3600
          update_cache: yes
  
      - name: Install main software packages [please wait]
        apt:
          name:
            - ansible
            - apt-transport-https
            - ca-certificates
            - containerd.io
            - curl
            - docker-ce
            - docker-ce-cli
            - docker-compose-plugin
            - git
            - gnupg
            - htop
            - inetutils-traceroute
            - lsb-release
            - mc
            - neofetch
            - net-tools
            - open-vm-tools
            - open-vm-tools-desktop
            - openssh-server
            - python3
            - python3-pip
            - python3-venv
            - snapd
            - snapd-xdg-open
            - software-properties-common
            - sqlitebrowser
            - sshpass
            - stunnel4
            - tcpdump
            - tcptrace
            - tcptraceroute
            - telnet
            - vim
            - vmfs-tools
            - visual-studio-code
            - wget
            - wireshark

          state: latest
          cache_valid_time: 3600
          update_cache: yes

      - name: Install snap software packages
        snap:
          name: 
            - drawio
            - postman
            - chromium
          state: present
      
      - name: Add vscode extension(s) for {{ciscouser}}
        become: false
        become_user: "{{ciscouser}}"
        command: code --install-extension ms-python.python

      - name: Install Python packages
        become: false
        become_user: "{{ciscouser}}"
        pip:
          name:
            - faker
            - flask
            - flask_restplus
            - ncclient
            - netmiko
            - pep8
            - pip
            - pipenv
            - pyang
            - pyats[full]
            - pylint
            - pyotp
            - requests
            - tabulate
            - ubuntu-mate-desktop
            - webexteamssdk
            - werkzeug
          state: latest
          extra_args: --break-system-packages

      - name: Create desktop shortcut for Firefox
        copy:
          dest: "/home/{{ ciscouser }}/Desktop/firefox.desktop"
          content: |
            [Desktop Entry]
            Name=Firefox
            Exec=firefox
            Icon=firefox
            Type=Application
            Terminal=false
        mode: '0755'

      # setup ansible configuration for the user
      - name: Ensure /etc/ansible exists
        ansible.builtin.file:
          path: "{{ etc_dir }}"
          state: directory
          owner: root
          group: root
          mode: "0755"

      - name: Download example ansible.cfg (do not overwrite by default)
        ansible.builtin.get_url:
          url: "{{ ansible_cfg_url }}"
          dest: "{{ cfg_path }}"
          owner: root
          group: root
          mode: "0644"
          force: "{{ overwrite_existing }}"
          backup: true
          # set use_proxy: yes if you need to obey proxy settings
        register: cfg_dl

      - name: Download example hosts (do not overwrite by default)
        ansible.builtin.get_url:
          url: "{{ hosts_url }}"
          dest: "{{ hosts_path }}"
          owner: root
          group: root
          mode: "0644"
          force: "{{ overwrite_existing }}"
          backup: true
        register: hosts_dl

      # Setup ssh authentication for the user
      - name: Ensure /etc/ssh/ssh_config exists
        ansible.builtin.file:
          path: "/etc/ssh/ssh_config"
          state: touch
          owner: root
          group: root
          mode: "0644"

      - name: Add (or update) global Host * block for legacy KEX and RSA
        ansible.builtin.blockinfile:
          path: "/etc/ssh/ssh_config"
          marker: "# {mark} ANSIBLE MANAGED BLOCK: legacy ssh algorithms for lab"
          backup: true
          create: true
          block: |
            Host *
                KexAlgorithms +diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
                HostkeyAlgorithms +ssh-rsa
                PubkeyAcceptedAlgorithms +ssh-rsa

    handlers:
      - name: Apt update
        apt:
          update_cache: true
      - name: Restart GDM
        service:
          name: gdm3
          state: restarted