---
- name: Add key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Add repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

- name: Install
  apt:
    name: code
    state: present
    update_cache: yes

- name: Hold
  command: apt-mark hold code
  when: vscode_disable_updates
